version: '3.5'
services:
  # appointments:
  #   build: './appointments'
  #   ports:
  #     - '3006:3006'
  #   networks:
  #     - ms_network
  swagger:
    build: './swagger'
    ports:
      - '3005:3005'
    networks:
      - ms_network
  users:
    build: '../TeazDealzapl_Users'
    ports:
      - '3004:3004'
    networks:
      - ms_network
  ads:
    build: '../TeazDealzAPI_Ads'
    ports:
      - '3003:3003'
    depends_on:
      - users
    networks:
      - ms_network
  tickets:
    build: '../TeazDealzAPI_Tickets'
    ports:
      - '3002:3002'
    depends_on:
      - users
    networks:
      - ms_network
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #   # depends_on:
  #     # - users
  #     # - ads
  #     # - swagger
  #     # - tickets
  #     # - appointments
  #   networks:
  #     - ms_network
networks:
  ms_network:
    driver: bridge
    name: ms_network
